# Generated by Django 4.2.6 on 2023-12-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('verificator', 'Verificator')], max_length=20),
        ),
    ]
