# Generated by Django 4.2.6 on 2023-10-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0002_alter_mediaitemtag_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='tag_names',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
