# Generated by Django 4.2.6 on 2023-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0006_mediaitem_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='arsipUI.tag'),
        ),
    ]
