# Generated by Django 4.2.6 on 2023-11-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0009_alter_mediaitem_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='category_name',
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='category',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('audio', 'Audio')], default='Image', max_length=5),
            preserve_default=False,
        ),
    ]
