# Generated by Django 4.2.6 on 2023-11-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0010_remove_mediaitem_category_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
