# Generated by Django 4.2.6 on 2023-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0011_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='tags',
            field=models.ManyToManyField(to='arsipUI.tag'),
        ),
    ]
