# Generated by Django 4.2.6 on 2023-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0013_alter_mediaitem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='reader_count',
            field=models.IntegerField(default=0),
        ),
    ]
