# Generated by Django 4.2.6 on 2023-11-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0014_mediaitem_reader_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='reader_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
