# Generated by Django 4.2.6 on 2023-11-30 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arsipUI', '0017_alter_mediaitem_contributor_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='contributor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
