# Generated by Django 4.2.6 on 2023-12-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0020_alter_mediaitem_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(blank=True, choices=[('waitlist', 'Waitlist'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=8),
        ),
    ]
