# Generated by Django 4.2.6 on 2023-12-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0021_mediaitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='event_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
