# Generated by Django 4.2.6 on 2023-12-03 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0022_event_category_mediaitem_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arsipUI.event_category'),
            preserve_default=False,
        ),
    ]
