# Generated by Django 4.2.6 on 2023-12-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0025_alter_mediaitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='arsipUI.tag'),
        ),
    ]
