# Generated by Django 4.2.6 on 2023-12-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0028_file_remove_mediaitem_file_path_mediaitem_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaitem',
            old_name='file_path',
            new_name='file_paths',
        ),
    ]
