# Generated by Django 4.2.6 on 2023-12-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0029_rename_file_path_mediaitem_file_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='category',
        ),
    ]
