# Generated by Django 4.2.6 on 2023-12-05 10:58

import arsipUI.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0030_remove_mediaitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='file_paths',
        ),
        migrations.AddField(
            model_name='file',
            name='media_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arsipUI.mediaitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to=arsipUI.models.media_file_path, validators=[arsipUI.models.validate_file_extension]),
        ),
    ]
