# Generated by Django 4.2.6 on 2023-12-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0033_mediaitem_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
    ]
