# Generated by Django 4.2.6 on 2023-12-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0034_alter_mediaitem_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='fakultas',
            field=models.CharField(blank=True, choices=[('FK', 'Fakultas Kedokteran'), ('FF', 'Fakultas Farmasi'), ('FIPB', 'Fakultas Ilmu Pengetahuan Budaya'), ('FH', 'Fakultas Hukum'), ('FT', 'Fakultas Teknik'), ('FEB', 'Fakultas Ekonomi dan Bisnis'), ('FISIP', 'Fakultas Ilmu Sosial dan Ilmu Politik'), ('FPsi', 'Fakultas Psikologi'), ('Fasilkom', 'Fakultas Ilmu Komputer'), ('FMIPA', 'Fakultas Matematika Dan Ilmu Pengetahuan Alam'), ('FIB', 'Fakultas Ilmu Budaya'), ('FKM', 'Fakultas Kesehatan Masyarakat'), ('FKG', 'Fakultas Kedokteran Gigi'), ('FIK', 'Fakultas Ilmu Keperawatan'), ('FIA', 'Fakultas Ilmu Administrasi'), ('PPV', 'Program Pendidikan Vokasi'), ('SIL', 'Sekolah Ilmu Pengetahuan'), ('SKSG', 'Sekolah Kajian Stratejik dan Global')], max_length=8),
        ),
    ]
