# Generated by Django 4.2.6 on 2023-12-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsipUI', '0035_mediaitem_fakultas'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('img', 'Images'), ('vid', 'Videos'), ('doc', 'Documents')], default='img', editable=False, max_length=3),
            preserve_default=False,
        ),
    ]
